### ISSUE TITLE
'distro' module dependency doesn't seem to be applied properly

### ISSUE THREAD

**Issue by ponte-vecchio** [kreat0/pyfetch#2]
I've installed pyfetch through AUR. Upon running the `pyfetch` command, it gave an error since I did not have `distro` module installed:

![](https://user-images.githubusercontent.com/64239070/117978173-f0a73400-b374-11eb-93bd-47192e6ae85b.png)

Installing it seemed to have fixed the error (see below):

![](https://user-images.githubusercontent.com/64239070/117978565-5a274280-b375-11eb-8145-38c966589c49.png)

edit: I've gone through the workflow file I can see that `distro` module is one of the modules to download, but perhaps it's not being applied properly?

**Comment by kreat0** [comment]
Seems like python-distro is on the community repos, do you have community repos enabled?

**Comment by ponte-vecchio** [comment]
> Seems like python-distro is on the community repos, do you have community repos enabled?

Yes indeed, and while I used `mamba` to install `distro` module from conda-forge, I've tried it again with pip and the same issue persists.

**Comment by kreat0** [comment]
> > Seems like python-distro is on the community repos, do you have community repos enabled?
> 
> Yes indeed, and while I used `mamba` to install `distro` module from conda-forge, I've tried it again with pip and the same issue persists.

Can you check if python-distro is installed or not?

**Comment by kreat0** [comment]
> > Seems like python-distro is on the community repos, do you have community repos enabled?
> 
> Yes indeed, and while I used `mamba` to install `distro` module from conda-forge, I've tried it again with pip and the same issue persists.

Can you check if python-distro is installed or not? Thats what we use in the AUR to install distro, so it should be installed if you installed it through AUR.
